include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

.deploy:
  environment:
    url: https://${CI_PROJECT_NAME}.${DD_TRAEFIK_DOMAIN}
