services:
  transmission:
    image: ${IMAGE_NAME:-lscr.io/linuxserver/transmission}:${IMAGE_TAG:-latest}
    environment:
      PUID:
      PGID:
      TZ:
      TRANSMISSION_WEB_HOME:
      USER:
      PASS:
      PEERPORT:
      HOST_WHITELIST: ${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}
    networks:
      traefik-net:
    ports:
      - target: ${PEERPORT}
        published: ${EXTERNAL_PEERPORT}
        protocol: tcp
        mode: ${PORT_MODE}
      - target: ${PEERPORT}
        published: ${EXTERNAL_PEERPORT}
        protocol: udp
        mode: ${PORT_MODE}
    volumes:
      - config-vol:/config
      - data-vol:/downloads
    healthcheck:
      test: wget --spider -q "http://${USER}:${PASS}@localhost:${UI_PORT}"
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}
        traefik.http.routers.transmission.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.transmission.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)
        traefik.http.services.transmission.loadbalancer.server.port: ${UI_PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-64M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

volumes:
  config-vol:
    name: ${CONFIG_VOL_NAME:-transmission-config-vol}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},vers=${VOL_VERS},${VOL_OPTS}
      device: :${VOL_DEVICE_PREFIX}${CONFIG_VOL_DEVICE:-/transmission-config-vol/}

  data-vol:
    name: ${DATA_VOL_NAME:-transmission-data-vol}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${DATA_VOL_TYPE}
      o: user=${DATA_VOL_USER},pass=${DATA_VOL_PASS},${DATA_VOL_OPTS}
      device: //${DATA_VOL_ADDR}/${DATA_VOL_PATH:-incoming}
