version: '3.7'

services:
  transmission:
    image: ${IMAGE_NAME:-linuxserver/transmission}:${IMAGE_TAG:-latest}
    environment:
      TZ:
    networks:
      - traefik-net
    ports:
      - target: ${TRANSMISSION_DATA_PORT}
        published: ${TRANSMISSION_DATA_PORT}
        protocol: tcp
        mode: ${TRANSMISSION_PORT_MODE}
      - target: ${TRANSMISSION_DATA_PORT}
        published: ${TRANSMISSION_DATA_PORT}
        protocol: udp
        mode: ${TRANSMISSION_PORT_MODE}
    volumes:
      - config-vol:/config
      - data-vol:/downloads
      - watch-vol:/watch
    healthcheck:
      test: wget --spider -q http://localhost:${TRANSMISSION_UI_PORT}
      interval: ${TRANSMISSION_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${TRANSMISSION_HEALTHCHECK_TIMEOUT:-1m}
      retries: ${TRANSMISSION_HEALTHCHECK_RETRIES:-3}
      start_period: ${TRANSMISSION_HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${TRANSMISSION_REPLICAS:-1}
      labels:
        traefik.frontend.auth.basic.users: ${TRANSMISSION_UI_AUTH}
        traefik.frontend.rule: Host:${TRANSMISSION_SUBDOMAIN:-transmission}.${PUBLIC_HOSTNAME}
        traefik.backend: transmission
        traefik.port: '${TRANSMISSION_UI_PORT}'
      restart_policy:
        delay: ${TRANSMISSION_RESTART_POLICY_DELAY:-10s}
        window: ${TRANSMISSION_RESTART_POLICY_WINDOW:-1m}
      resources:
        limits:
          cpus: '${TRANSMISSION_LIMITS_CPUS:-1}'
          memory: ${TRANSMISSION_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${TRANSMISSION_RESERVATIONS_CPUS:-0.001}'
          memory: ${TRANSMISSION_RESERVATIONS_MEMORY:-32M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

volumes:
  data-vol:
    name: ${TRANSMISSION_DATA_VOL_NAME:-transmission-data-vol}
    driver: local
    driver_opts:
      type: ${TRANSMISSION_DATA_VOLUME_TYPE}
      o: ${TRANSMISSION_DATA_VOLUME_OPTIONS}
      device: ${TRANSMISSION_DATA_VOLUME_DEVICE}

  config-vol:
    name: ${TRANSMISSION_CONFIG_VOL_NAME:-transmission-config-vol}
    driver: local
    driver_opts:
      type: ${TRANSMISSION_CONFIG_VOLUME_TYPE}
      o: ${TRANSMISSION_CONFIG_VOLUME_OPTIONS}
      device: ${TRANSMISSION_CONFIG_VOLUME_DEVICE}

  watch-vol:
    name: ${TRANSMISSION_WATCH_VOL_NAME:-transmission-watch-vol}
