version: '3.7'
services:
  transmission:
    image: ${IMAGE_NAME:-linuxserver/transmission}:${IMAGE_TAG:-latest}
    environment:
      - TZ
    networks:
      - traefik-net
    ports:
      - target: ${DATA_PORT}
        published: ${DATA_PORT}
        protocol: tcp
        mode: host
      - target: ${DATA_PORT}
        published: ${DATA_PORT}
        protocol: udp
        mode: host
    volumes:
      - config-vol:/config
      - data-vol:/downloads
      - watch-vol:/watch
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.docker.network: traefik-net
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:transmission.${PUBLIC_HOSTNAME}
        traefik.backend: transmission
        traefik.port: "${UI_PORT}"
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          memory: 64M

networks:
  traefik-net:
    external: true

volumes:
  data-vol:
    driver: local
    driver_opts:
      type: ${DATA_VOLUME_TYPE}
      o: ${DATA_VOLUME_OPTIONS}
      device: ${DATA_VOLUME_DEVICE}

  config-vol:
    name: transmission-config-vol

  watch-vol:
    name: transmission-watch-vol
