version: '3.7'
services:
  transmission:
    image: ${IMAGE_NAME:-linuxserver/transmission}:${IMAGE_TAG:-latest}
    environment:
      - TZ
    networks:
      - traefik-net
    ports:
      - target: ${DATA_PORT}
        published: ${DATA_PORT}
        protocol: tcp
        mode: ${PORT_MODE}
      - target: ${DATA_PORT}
        published: ${DATA_PORT}
        protocol: udp
        mode: ${PORT_MODE}
    volumes:
      - config-vol:/config
      - data-vol:/downloads
      - watch-vol:/watch
    healthcheck:
      test: wget --spider -nv -t 3 http://localhost:${UI_PORT}
      interval: ${TRANSMISSION_HEALTHCHECK_INTERVAL}
      timeout: ${TRANSMISSION_HEALTHCHECK_TIMEOUT}
      retries: ${TRANSMISSION_HEALTHCHECK_RETRIES}
      start_period: ${TRANSMISSION_HEALTHCHECK_START_PERIOD}
    deploy:
      mode: replicated
      replicas: ${TRANSMISSION_REPLICAS}
      labels:
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:${SUBDOMAIN}.${PUBLIC_HOSTNAME}
        traefik.backend: transmission
        traefik.port: "${UI_PORT}"
      restart_policy:
        delay: ${TRANSMISSION_RESTART_POLICY_DELAY}
        window: ${TRANSMISSION_RESTART_POLICY_WINDOW}
      resources:
        limits:
          cpus: "${TRANSMISSION_LIMITS_CPUS}"
          memory: ${TRANSMISSION_LIMITS_MEMORY}
        reservations:
          memory: ${TRANSMISSION_RESERVATIONS_MEMORY}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

volumes:
  data-vol:
    name: ${TRANSMISSION_DATA_VOL_NAME:-transmission-data-vol}
    driver: local
    driver_opts:
      type: ${DATA_VOLUME_TYPE}
      o: ${DATA_VOLUME_OPTIONS}
      device: ${DATA_VOLUME_DEVICE}

  config-vol:
    name: ${TRANSMISSION_CONFIG_VOL_NAME:-transmission-config-vol}

  watch-vol:
    name: ${TRANSMISSION_WATCH_VOL_NAME:-transmission-watch-vol}
